# This file will install the below packages in ~/.cache/pre-commit/
# pre-commit will use those packages. It won't use the packages installed by pipenv
# So no need to install black, flake8 etc in the pipenv

repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v1.2.3
  hooks:
  - id: flake8
    files: ^(frontend)/
    exclude: ^uniq/
    additional_dependencies: ['pep8-naming']
    language_version: python3
- repo: https://github.com/ambv/black
  rev: 6bedb5c58a7d8c25aa9509f8217bc24e9797e90d # We are using commit sha1sum for v18.9b0 because of pre-commit bug
  hooks:
  - id: black
    files: ^(frontend)/
    exclude: ^uniq/
    language_version: python3
- repo: local
  hooks:
  - id: seed-isort-config
    name: custom-seed-isort-config
    entry: seed-isort-config
    args: ["--exclude", "(frontend)"]
    pass_filenames: False
    language_version: python3
    language: python
- repo: https://github.com/pre-commit/mirrors-isort
  rev: v4.3.4
  hooks:
  - id: isort
    files: ^(frontend)/
    exclude: ^uniq/
    args: ["-l", "120"]
    language_version: python3
